smachを用いたサンプルを追加
IRSL-tut/irsl_choreonoid_ros pull request #14
Opened 2023-06-21 01:44 UTC by Hiroaki-Masuzawa

元々あったサンプルプログラムを基にsmachとRIを使用するものを作成しました．

2023-06-21 11:50 UTC, YoheiKakiuchi requested changes

2023-06-21 23:50 UTC, Hiroaki-Masuzawa commented on sample/motionlib.py
> +      if tof_data.data > 0.5:
チェックの順間違えていました．修正しました．

2023-06-21 23:53 UTC, Hiroaki-Masuzawa commented on sample/ReadMe.md
> +source /opt/ros/noetic/setup.bash
irsl_docker_irsl_system内の`run_sim_local.sh`で実行したコンテナに対してdocker execで入った場合には，`source /opt/ros/noetic/setup.bash`が必要だったため記載しております．私の想定環境が違うのでしょうか？

2023-06-22 01:14 UTC, YoheiKakiuchi commented on sample/ReadMe.md
> +source /opt/ros/noetic/setup.bash
どういうメッセージがでてどういう不具合になりますか？
ROSのワークスペースはカスケードなので、上位のsetup.shは下位に含まれているはずなんですよね。

2023-06-22 02:57 UTC, Hiroaki-Masuzawa commented on sample/ReadMe.md
> +source /opt/ros/noetic/setup.bash
確認実行手順が悪かったようです．
単純に
`python3 stop_robot_ri.py`
でrospyのインポートエラーが出たので
`source /opt/ros/noetic/setup.bash`
を実行したのち，再度実行したときにirsl_choreonoid_rosのインポートエラーが出て...という
対処を行ったときの手順を記載したためこのようになりました．
内容修正しております．

2023-06-22 04:56 UTC, YoheiKakiuchi approved these changes

2023-06-22 04:57 UTC, merged